filter:
    paths: ['extensions/libraries/twig/src']
checks:
    php: true
coding_style:
    php:
        indentation:
            general:
                use_tabs: true
        spaces:
            around_operators:
                concatenation: true
build:
    environment:
        php:
            version: 7.1
    tests:
        before:
            - ./ci/setup.sh
        override:
            -
                command: ./vendor/bin/phpunit --configuration ci/phpunit.ci.xml --coverage-clover ./clover.xml
                coverage:
                    file: clover.xml
                    format: clover