sudo: required

language: php

addons:
  sonarcloud:
    organization: "phproberto-github"
    token:
      secure: "$SONAR_TOKEN"
      
jdk:
  - oraclejdk8

cache:
  directories:
    - '$HOME/.sonar/cache'

php:
  - 7.0.21
  - 7.1

branches:
  only:
  - master
  - develop

before_script:
  - ./ci/setup.sh

script:
  - ./ci/test.sh
  - sonar-scanner
  