sudo: false

language: php

php:
  - 7.0.21
  - 7.1

branches:
  only:
  - master
  - develop
script:
  - composer install --prefer-dist --no-interaction --no-progress
  - ./vendor/bin/phpcs --standard="ruleset.xml"
  - git clone https://github.com/joomla/joomla-cms.git /tmp/joomla-cms
  - composer install -d /tmp/joomla-cms
  - composer install -d ./extensions/libraries/twig
  - ./vendor/bin/phpunit --configuration ci/phpunit.ci.xml