show_nav: false
show_sidebar: true
show_downloads: true
download_url: https://github.com/phproberto/joomla-twig/releases/download/v1.0.0-beta2/joomla-twig-v1.0.0-beta2.zip
theme: phproberto/jekyll-test
remote_theme: "phproberto/jekyll-test"
plugins:
  - jekyll-remote-theme
